name: 'Manual Version Bump'
description: 'Manual action for bumping of semver tag and optional release'
author: 'lajosbencz'

runs:
  using: node20
  main: dist/index.js

branding:
  icon: 'tag'
  color: 'red'

inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

outputs:
  time:
    description: 'Your output description here'
