name: 'Manual Version Bump'
description: 'Manual action for bumping of semver tag and optional release'
author: 'lajosbencz'

runs:
  using: node20
  main: dist/index.js

branding:
  icon: tag
  color: red

inputs:
  release_type:
    description: 'Which SemVer level to bump (major/minor/patch)'
    required: true
    default: patch
  push:
    description: 'Whether to tag and push to the remote repository'
    required: false
    default: 'true'
  filter:
    description: 'Filter for the tag to bump, for eg: 1.2'
    required: false
  prefix_with_v:
    description: 'Whether to prefix the version with a "v"'
    required: false
    default: 'true'
  prerelease_identifier_base:
    description: 'Prerelease Identifier Base'
    required: false
  commit_hash:
    description: 'The commit hash to tag'
    required: false
    default: HEAD

  milliseconds:
    description: 'Milliseconds to wait before the action starts'
    required: false
    default: '500'

outputs:
  time:
    description: 'Your output description here'
