name: 'Manual Version Bump'
description: 'Manual action for bumping of semver tag and optional release'
author: 'lajosbencz'

runs:
  using: node20
  main: dist/index.js

branding:
  icon: tag
  color: red

inputs:
  release_type:
    description: 'Which SemVer level to bump (major/minor/patch)'
    required: true
    default: patch
  push:
    description: 'Whether to tag and push to the remote repository'
    required: false
    default: 'false'
  filter:
    description: 'Filter for the tag to bump, for eg: 1.2'
    required: false
  prefix_with_v:
    description: 'Whether to prefix the version with a "v"'
    required: false
    default: 'true'
  prerelease_identifier_base:
    description: 'Prerelease Identifier Base'
    required: false
  commit_hash:
    description: 'The commit hash to tag'
    required: false
    default: HEAD
  commiter_name:
    description: 'The name of the commiter'
    required: false
    default: github-actions
  commiter_email:
    description: 'The email of the commiter'
    required: false
    default: github-actions@github.com

outputs:
  old_tag:
    description: 'Latest tag before bump'
  new_tag:
    description: 'New tag after bump'
