#!/usr/bin/env sh

if ! git diff-index --cached --quiet HEAD -- src/ >/dev/null; then
  echo "Changes detected in src/ folder. Running package..."
  npm run package
  git add dist/
  git commit --amend --no-edit --no-verify
  echo "Build committed."
fi
