#!/usr/bin/env sh

if ! git diff-index --cached --quiet HEAD -- src/; then
  echo "Changes detected in src/ folder packaging..."
  npm run package
  git add dist/
  git commit --amend --no-edit --no-verify
  echo "Build committed."
else
  echo "No need to package"
fi
