name: Manual Version Bump

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Which SemVer level to bump'
        type: choice
        required: true
        default: patch
        options:
          - major
          - premajor
          - minor
          - preminor
          - patch
          - prepatch
          - prerelease
      prefix_with_v:
        description: 'Prefix the version with a "v"'
        type: choice
        required: false
        default: 'true'
        options:
          - 'true'
          - 'false'
      prerelease_identifier_base:
        description: 'Prerelease Identifier Base'
        required: false

permissions:
  contents: write

jobs:
  bump:
    name: Bump Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Calculate new tag
        id: tag
        uses: ./
        with:
          release_type: '${{ github.event.inputs.release_type }}'
          push: 'false'
          filter: '${{ github.event.inputs.filter }}'
          prefix_with_v: '${{ github.event.inputs.prefix_with_v }}'
          prerelease_identifier_base:
            '${{ github.event.inputs.prerelease_identifier_base }}'
          commit_hash: '${{ github.event.inputs.commit_hash }}'

      - name: Update package.json version
        run: 'script/npm-version ${{ steps.tag.outputs.new_tag_semver }}'

      - name: Commit package.json version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: bump package.json version
          file_pattern: 'package.json'

      - name: Run Local Action
        id: tag-push
        uses: ./
        with:
          release_type: '${{ github.event.inputs.release_type }}'
          push: 'true'
          filter: '${{ github.event.inputs.filter }}'
          prefix_with_v: '${{ github.event.inputs.prefix_with_v }}'
          prerelease_identifier_base:
            '${{ github.event.inputs.prerelease_identifier_base }}'
          commit_hash: '${{ github.event.inputs.commit_hash }}'

      - name: Print Output
        id: output
        run: |
          echo "semver:"
          echo "  old: ${{ steps.tag.outputs.old_tag_semver }}"
          echo "  new: ${{ steps.tag.outputs.new_tag_semver }}"
          echo "tag:"
          echo "  old: ${{ steps.tag.outputs.old_tag }}"
          echo "  new: ${{ steps.tag.outputs.new_tag }}"
