name: Manual Version Bump

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Which SemVer level to bump'
        type: choice
        required: true
        default: patch
        options:
          - major
          - premajor
          - minor
          - preminor
          - patch
          - prepatch
          - prerelease
      push:
        description: 'Tag and push to the remote repository'
        type: choice
        required: false
        default: 'false'
        options:
          - true
          - false
      filter:
        description: 'Filter for the tag to bump, for eg: 1.2'
        required: false
      prefix_with_v:
        description: 'Prefix the version with a "v"'
        type: choice
        required: false
        default: 'true'
        options:
          - 'true'
          - 'false'
      prerelease_identifier_base:
        description: 'Prerelease Identifier Base'
        required: false
      commit_hash:
        description: 'The commit hash to tag'
        required: false
        default: HEAD

permissions:
  contents: write

jobs:
  bump:
    name: Bump Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run Local Action
        id: run
        uses: ./

      - name: Print Output
        id: output
        run: |
          echo "Bumped from ${{ steps.run.outputs.old_tag }} to ${{ steps.run.outputs.new_tag }}"
