name: Manual Version Bump

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump:
    name: Bump Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run Local Action
        id: run
        uses: ./

      - name: Print Output
        id: output
        run: echo "${{ steps.run.outputs.time }}"
